// Code generated by capnpc-go. DO NOT EDIT.

package server

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	datura "github.com/theapemachine/datura"
)

type Server capnp.Client

// Server_TypeID is the unique identifier for the type Server.
const Server_TypeID = 0xca6cd8732fa23c4c

func (c Server) Write(ctx context.Context, params func(Server_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xca6cd8732fa23c4c,
			MethodID:      0,
			InterfaceName: "dmt/server/server.capnp:Server",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Server_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Server) Done(ctx context.Context, params func(Server_done_Params) error) (Server_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xca6cd8732fa23c4c,
			MethodID:      1,
			InterfaceName: "dmt/server/server.capnp:Server",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Server_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Server_done_Results_Future{Future: ans.Future()}, release

}

func (c Server) Lookup(ctx context.Context, params func(Server_lookup_Params) error) (Server_lookup_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xca6cd8732fa23c4c,
			MethodID:      2,
			InterfaceName: "dmt/server/server.capnp:Server",
			MethodName:    "lookup",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Server_lookup_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Server_lookup_Results_Future{Future: ans.Future()}, release

}

func (c Server) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Server) String() string {
	return "Server(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Server) AddRef() Server {
	return Server(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Server) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Server) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Server) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Server) DecodeFromPtr(p capnp.Ptr) Server {
	return Server(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Server) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Server) IsSame(other Server) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Server) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Server) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Server_Server is a Server with a local implementation.
type Server_Server interface {
	Write(context.Context, Server_write) error

	Done(context.Context, Server_done) error

	Lookup(context.Context, Server_lookup) error
}

// Server_NewServer creates a new Server from an implementation of Server_Server.
func Server_NewServer(s Server_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Server_Methods(nil, s), s, c)
}

// Server_ServerToClient creates a new Client from an implementation of Server_Server.
// The caller is responsible for calling Release on the returned Client.
func Server_ServerToClient(s Server_Server) Server {
	return Server(capnp.NewClient(Server_NewServer(s)))
}

// Server_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Server_Methods(methods []server.Method, s Server_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 3)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xca6cd8732fa23c4c,
			MethodID:      0,
			InterfaceName: "dmt/server/server.capnp:Server",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Server_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xca6cd8732fa23c4c,
			MethodID:      1,
			InterfaceName: "dmt/server/server.capnp:Server",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Server_done{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xca6cd8732fa23c4c,
			MethodID:      2,
			InterfaceName: "dmt/server/server.capnp:Server",
			MethodName:    "lookup",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Lookup(ctx, Server_lookup{call})
		},
	})

	return methods
}

// Server_write holds the state for a server call to Server.write.
// See server.Call for documentation.
type Server_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Server_write) Args() Server_write_Params {
	return Server_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Server_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Server_done holds the state for a server call to Server.done.
// See server.Call for documentation.
type Server_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Server_done) Args() Server_done_Params {
	return Server_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Server_done) AllocResults() (Server_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Server_done_Results(r), err
}

// Server_lookup holds the state for a server call to Server.lookup.
// See server.Call for documentation.
type Server_lookup struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Server_lookup) Args() Server_lookup_Params {
	return Server_lookup_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Server_lookup) AllocResults() (Server_lookup_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Server_lookup_Results(r), err
}

// Server_List is a list of Server.
type Server_List = capnp.CapList[Server]

// NewServer_List creates a new list of Server.
func NewServer_List(s *capnp.Segment, sz int32) (Server_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Server](l), err
}

type Server_write_Params capnp.Struct

// Server_write_Params_TypeID is the unique identifier for the type Server_write_Params.
const Server_write_Params_TypeID = 0x96bc5658c7ccbfb4

func NewServer_write_Params(s *capnp.Segment) (Server_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Server_write_Params(st), err
}

func NewRootServer_write_Params(s *capnp.Segment) (Server_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Server_write_Params(st), err
}

func ReadRootServer_write_Params(msg *capnp.Message) (Server_write_Params, error) {
	root, err := msg.Root()
	return Server_write_Params(root.Struct()), err
}

func (s Server_write_Params) String() string {
	str, _ := text.Marshal(0x96bc5658c7ccbfb4, capnp.Struct(s))
	return str
}

func (s Server_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Server_write_Params) DecodeFromPtr(p capnp.Ptr) Server_write_Params {
	return Server_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Server_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Server_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Server_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Server_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Server_write_Params) Key() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Server_write_Params) SetKey(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Server_write_Params) Value() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Server_write_Params) HasValue() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Server_write_Params) SetValue(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// Server_write_Params_List is a list of Server_write_Params.
type Server_write_Params_List = capnp.StructList[Server_write_Params]

// NewServer_write_Params creates a new list of Server_write_Params.
func NewServer_write_Params_List(s *capnp.Segment, sz int32) (Server_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Server_write_Params](l), err
}

// Server_write_Params_Future is a wrapper for a Server_write_Params promised by a client call.
type Server_write_Params_Future struct{ *capnp.Future }

func (f Server_write_Params_Future) Struct() (Server_write_Params, error) {
	p, err := f.Future.Ptr()
	return Server_write_Params(p.Struct()), err
}

type Server_done_Params capnp.Struct

// Server_done_Params_TypeID is the unique identifier for the type Server_done_Params.
const Server_done_Params_TypeID = 0xe347c2d4de9c6184

func NewServer_done_Params(s *capnp.Segment) (Server_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Server_done_Params(st), err
}

func NewRootServer_done_Params(s *capnp.Segment) (Server_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Server_done_Params(st), err
}

func ReadRootServer_done_Params(msg *capnp.Message) (Server_done_Params, error) {
	root, err := msg.Root()
	return Server_done_Params(root.Struct()), err
}

func (s Server_done_Params) String() string {
	str, _ := text.Marshal(0xe347c2d4de9c6184, capnp.Struct(s))
	return str
}

func (s Server_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Server_done_Params) DecodeFromPtr(p capnp.Ptr) Server_done_Params {
	return Server_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Server_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Server_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Server_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Server_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Server_done_Params_List is a list of Server_done_Params.
type Server_done_Params_List = capnp.StructList[Server_done_Params]

// NewServer_done_Params creates a new list of Server_done_Params.
func NewServer_done_Params_List(s *capnp.Segment, sz int32) (Server_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Server_done_Params](l), err
}

// Server_done_Params_Future is a wrapper for a Server_done_Params promised by a client call.
type Server_done_Params_Future struct{ *capnp.Future }

func (f Server_done_Params_Future) Struct() (Server_done_Params, error) {
	p, err := f.Future.Ptr()
	return Server_done_Params(p.Struct()), err
}

type Server_done_Results capnp.Struct

// Server_done_Results_TypeID is the unique identifier for the type Server_done_Results.
const Server_done_Results_TypeID = 0xf63d8f3bbfb372ba

func NewServer_done_Results(s *capnp.Segment) (Server_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Server_done_Results(st), err
}

func NewRootServer_done_Results(s *capnp.Segment) (Server_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Server_done_Results(st), err
}

func ReadRootServer_done_Results(msg *capnp.Message) (Server_done_Results, error) {
	root, err := msg.Root()
	return Server_done_Results(root.Struct()), err
}

func (s Server_done_Results) String() string {
	str, _ := text.Marshal(0xf63d8f3bbfb372ba, capnp.Struct(s))
	return str
}

func (s Server_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Server_done_Results) DecodeFromPtr(p capnp.Ptr) Server_done_Results {
	return Server_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Server_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Server_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Server_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Server_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Server_done_Results_List is a list of Server_done_Results.
type Server_done_Results_List = capnp.StructList[Server_done_Results]

// NewServer_done_Results creates a new list of Server_done_Results.
func NewServer_done_Results_List(s *capnp.Segment, sz int32) (Server_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Server_done_Results](l), err
}

// Server_done_Results_Future is a wrapper for a Server_done_Results promised by a client call.
type Server_done_Results_Future struct{ *capnp.Future }

func (f Server_done_Results_Future) Struct() (Server_done_Results, error) {
	p, err := f.Future.Ptr()
	return Server_done_Results(p.Struct()), err
}

type Server_lookup_Params capnp.Struct

// Server_lookup_Params_TypeID is the unique identifier for the type Server_lookup_Params.
const Server_lookup_Params_TypeID = 0xedde37ccb1d51348

func NewServer_lookup_Params(s *capnp.Segment) (Server_lookup_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Server_lookup_Params(st), err
}

func NewRootServer_lookup_Params(s *capnp.Segment) (Server_lookup_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Server_lookup_Params(st), err
}

func ReadRootServer_lookup_Params(msg *capnp.Message) (Server_lookup_Params, error) {
	root, err := msg.Root()
	return Server_lookup_Params(root.Struct()), err
}

func (s Server_lookup_Params) String() string {
	str, _ := text.Marshal(0xedde37ccb1d51348, capnp.Struct(s))
	return str
}

func (s Server_lookup_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Server_lookup_Params) DecodeFromPtr(p capnp.Ptr) Server_lookup_Params {
	return Server_lookup_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Server_lookup_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Server_lookup_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Server_lookup_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Server_lookup_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Server_lookup_Params) Keys() (capnp.UInt64List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.UInt64List(p.List()), err
}

func (s Server_lookup_Params) HasKeys() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Server_lookup_Params) SetKeys(v capnp.UInt64List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewKeys sets the keys field to a newly
// allocated capnp.UInt64List, preferring placement in s's segment.
func (s Server_lookup_Params) NewKeys(n int32) (capnp.UInt64List, error) {
	l, err := capnp.NewUInt64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt64List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Server_lookup_Params_List is a list of Server_lookup_Params.
type Server_lookup_Params_List = capnp.StructList[Server_lookup_Params]

// NewServer_lookup_Params creates a new list of Server_lookup_Params.
func NewServer_lookup_Params_List(s *capnp.Segment, sz int32) (Server_lookup_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Server_lookup_Params](l), err
}

// Server_lookup_Params_Future is a wrapper for a Server_lookup_Params promised by a client call.
type Server_lookup_Params_Future struct{ *capnp.Future }

func (f Server_lookup_Params_Future) Struct() (Server_lookup_Params, error) {
	p, err := f.Future.Ptr()
	return Server_lookup_Params(p.Struct()), err
}

type Server_lookup_Results capnp.Struct

// Server_lookup_Results_TypeID is the unique identifier for the type Server_lookup_Results.
const Server_lookup_Results_TypeID = 0xac22651dc2e01910

func NewServer_lookup_Results(s *capnp.Segment) (Server_lookup_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Server_lookup_Results(st), err
}

func NewRootServer_lookup_Results(s *capnp.Segment) (Server_lookup_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Server_lookup_Results(st), err
}

func ReadRootServer_lookup_Results(msg *capnp.Message) (Server_lookup_Results, error) {
	root, err := msg.Root()
	return Server_lookup_Results(root.Struct()), err
}

func (s Server_lookup_Results) String() string {
	str, _ := text.Marshal(0xac22651dc2e01910, capnp.Struct(s))
	return str
}

func (s Server_lookup_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Server_lookup_Results) DecodeFromPtr(p capnp.Ptr) Server_lookup_Results {
	return Server_lookup_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Server_lookup_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Server_lookup_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Server_lookup_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Server_lookup_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Server_lookup_Results) Values() (datura.Artifact_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return datura.Artifact_List(p.List()), err
}

func (s Server_lookup_Results) HasValues() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Server_lookup_Results) SetValues(v datura.Artifact_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewValues sets the values field to a newly
// allocated datura.Artifact_List, preferring placement in s's segment.
func (s Server_lookup_Results) NewValues(n int32) (datura.Artifact_List, error) {
	l, err := datura.NewArtifact_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return datura.Artifact_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Server_lookup_Results_List is a list of Server_lookup_Results.
type Server_lookup_Results_List = capnp.StructList[Server_lookup_Results]

// NewServer_lookup_Results creates a new list of Server_lookup_Results.
func NewServer_lookup_Results_List(s *capnp.Segment, sz int32) (Server_lookup_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Server_lookup_Results](l), err
}

// Server_lookup_Results_Future is a wrapper for a Server_lookup_Results promised by a client call.
type Server_lookup_Results_Future struct{ *capnp.Future }

func (f Server_lookup_Results_Future) Struct() (Server_lookup_Results, error) {
	p, err := f.Future.Ptr()
	return Server_lookup_Results(p.Struct()), err
}

const schema_ad058c9d70413d66 = "x\xda\x8c\x91?h\x13o\x18\xc7\xbf\xdf\xf7\xde\xfb]" +
	"\x02\xbf$=\xce\x80\x0e\x12,\x19\xb4\x12[\x1bA\x8c" +
	"\x86\xc4A\xea\xe0\x90\xb7\x82\x88\x8b^\xed+h\xfez" +
	"\x97k\xe8\xe0\xe6(\xb8\x89\x8a.\xceV\x08\xea\xa0\x08" +
	"\x95.\x85\xd2Q\xc1\xa9\x08\xe2\xe8\xaa\xe0r\xf2&\xf4" +
	"\x0c.\xedt\xdc\xfb>\xcf\xf3y\x9f\xcfw\xee1\xeb" +
	"\xf2df!\x05\xa1n\xd8\xff\xc5o\xd6\xb77\xaf^" +
	"\xf9\xf0\x08\xaa@\x026\x1d\xa0\x9c\x96K\x04\xbd\xbc\x1c" +
	"\x80\xf1\xd4\xa1\xaf\x1b\x87\xf5\xf4K\xb8\x85\xa4\xe0\xae\x0c" +
	"L\xc1=Y\x03\xe3K\xe7^\xcc\x86_Z[p\x0f" +
	"Z\xf1\xad\xea\xf9\xde\xf3\x07\xf6\x1a@oM\xfe\xf6\xde" +
	"I\x07\xf0\xde\xcaM\xafd;@|\xdf\x7f\xb6\xf3i" +
	"c\xe1\xdbx\x9a\xb9,\xe7\xedk\x84\x8c/z\x9f\x87" +
	"\xdb\xa7w~Lrh\xdf1\x9c\x8cm8\xef\x83\xd7" +
	"\xebg\x1fV\x7fN\xb4V\xed%b+^n\xf7g" +
	"C\x1d\xacH\x1d\x8c\xbe:8q\xd3\xefuz\x95\xcb" +
	"\xe3\x9fAp\xbb\xaf\x8b\x0d?p\xfcv\xa8R\x96\x04" +
	"$\x01\xf7\xd84\xa0\x8a\x16\xd5\x9c y\xc0\x08pK" +
	"\xf3\x80:jQ\x9d\x12t\x9az\x95i\x08\xa6\xc1\xc2" +
	"\x8a\xdf\x8a43\x10\xcc\x80{\"[\xddn3\xea\x15" +
	"\x17u!\x8cZ\xfdP\xc9\x04\x9a\xa9\x00*eQ\x15" +
	"\x05k\xa3\xa1!\xb3`\xc3\"\xa7~}\x8f^e\x8f" +
	"\xa7\x87\xa09J \xe2_HmLi\x90\xea\x7f\xcb" +
	"\x06\x92\x18\xd9\x19~\x1c\x94\x9f^\x7f\xe2\xaay\x08\xf7" +
	"\x82C&\xca\xb9+\xd0=3\x03\xe1\x96\x1c\x8aD:" +
	"wSv\x8fT \xdc\xbcS\x189\xab3\xb7\xdc\xed" +
	"\xe8:k\xe3}\xealp\xef\xddM\x8b\xb1\xed[\xed" +
	"p\xbf\xa2\x1a~.0\xe1Lx\x9a\xf9\xeb)\xd7\xd4" +
	"\xab\x89%\x13H\x16\xfb|\xc6\xa2\x0e#\xa7\xd5\x0f\xff" +
	"\x04\x00\x00\xff\xff\x83\xee\xd6:"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ad058c9d70413d66,
		Nodes: []uint64{
			0x96bc5658c7ccbfb4,
			0xac22651dc2e01910,
			0xca6cd8732fa23c4c,
			0xe347c2d4de9c6184,
			0xedde37ccb1d51348,
			0xf63d8f3bbfb372ba,
		},
		Compressed: true,
	})
}
