// Code generated by capnpc-go. DO NOT EDIT.

package datura

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
	strconv "strconv"
)

type Artifact capnp.Struct

// Artifact_TypeID is the unique identifier for the type Artifact.
const Artifact_TypeID = 0xb1092b0e00ae75e5

func NewArtifact(s *capnp.Segment) (Artifact, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 15})
	return Artifact(st), err
}

func NewRootArtifact(s *capnp.Segment) (Artifact, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 15})
	return Artifact(st), err
}

func ReadRootArtifact(msg *capnp.Message) (Artifact, error) {
	root, err := msg.Root()
	return Artifact(root.Struct()), err
}

func (s Artifact) String() string {
	str, _ := text.Marshal(0xb1092b0e00ae75e5, capnp.Struct(s))
	return str
}

func (s Artifact) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Artifact) DecodeFromPtr(p capnp.Ptr) Artifact {
	return Artifact(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Artifact) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Artifact) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Artifact) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Artifact) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Artifact) Uuid() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Artifact) HasUuid() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Artifact) SetUuid(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Artifact) Checksum() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s Artifact) HasChecksum() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Artifact) SetChecksum(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

func (s Artifact) Timestamp() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s Artifact) SetTimestamp(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s Artifact) Error() (Artifact_Error, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return Artifact_Error(p.Struct()), err
}

func (s Artifact) HasError() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Artifact) SetError(v Artifact_Error) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewError sets the error field to a newly
// allocated Artifact_Error struct, preferring placement in s's segment.
func (s Artifact) NewError() (Artifact_Error, error) {
	ss, err := NewArtifact_Error(capnp.Struct(s).Segment())
	if err != nil {
		return Artifact_Error{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Artifact) PseudonymHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return []byte(p.Data()), err
}

func (s Artifact) HasPseudonymHash() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Artifact) SetPseudonymHash(v []byte) error {
	return capnp.Struct(s).SetData(3, v)
}

func (s Artifact) MerkleRoot() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return []byte(p.Data()), err
}

func (s Artifact) HasMerkleRoot() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Artifact) SetMerkleRoot(v []byte) error {
	return capnp.Struct(s).SetData(4, v)
}

func (s Artifact) Type() Artifact_Type {
	return Artifact_Type(capnp.Struct(s).Uint16(8))
}

func (s Artifact) SetType(v Artifact_Type) {
	capnp.Struct(s).SetUint16(8, uint16(v))
}

func (s Artifact) Origin() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s Artifact) HasOrigin() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Artifact) OriginBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s Artifact) SetOrigin(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s Artifact) Destination() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s Artifact) HasDestination() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s Artifact) DestinationBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s Artifact) SetDestination(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s Artifact) Role() (string, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.Text(), err
}

func (s Artifact) HasRole() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s Artifact) RoleBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.TextBytes(), err
}

func (s Artifact) SetRole(v string) error {
	return capnp.Struct(s).SetText(7, v)
}

func (s Artifact) Scope() (string, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.Text(), err
}

func (s Artifact) HasScope() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s Artifact) ScopeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.TextBytes(), err
}

func (s Artifact) SetScope(v string) error {
	return capnp.Struct(s).SetText(8, v)
}

func (s Artifact) Attributes() (Artifact_Attribute_List, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return Artifact_Attribute_List(p.List()), err
}

func (s Artifact) HasAttributes() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s Artifact) SetAttributes(v Artifact_Attribute_List) error {
	return capnp.Struct(s).SetPtr(9, v.ToPtr())
}

// NewAttributes sets the attributes field to a newly
// allocated Artifact_Attribute_List, preferring placement in s's segment.
func (s Artifact) NewAttributes(n int32) (Artifact_Attribute_List, error) {
	l, err := NewArtifact_Attribute_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Artifact_Attribute_List{}, err
	}
	err = capnp.Struct(s).SetPtr(9, l.ToPtr())
	return l, err
}
func (s Artifact) EncryptedPayload() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return []byte(p.Data()), err
}

func (s Artifact) HasEncryptedPayload() bool {
	return capnp.Struct(s).HasPtr(10)
}

func (s Artifact) SetEncryptedPayload(v []byte) error {
	return capnp.Struct(s).SetData(10, v)
}

func (s Artifact) EncryptedKey() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(11)
	return []byte(p.Data()), err
}

func (s Artifact) HasEncryptedKey() bool {
	return capnp.Struct(s).HasPtr(11)
}

func (s Artifact) SetEncryptedKey(v []byte) error {
	return capnp.Struct(s).SetData(11, v)
}

func (s Artifact) EphemeralPublicKey() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(12)
	return []byte(p.Data()), err
}

func (s Artifact) HasEphemeralPublicKey() bool {
	return capnp.Struct(s).HasPtr(12)
}

func (s Artifact) SetEphemeralPublicKey(v []byte) error {
	return capnp.Struct(s).SetData(12, v)
}

func (s Artifact) Approvals() (Artifact_Approval_List, error) {
	p, err := capnp.Struct(s).Ptr(13)
	return Artifact_Approval_List(p.List()), err
}

func (s Artifact) HasApprovals() bool {
	return capnp.Struct(s).HasPtr(13)
}

func (s Artifact) SetApprovals(v Artifact_Approval_List) error {
	return capnp.Struct(s).SetPtr(13, v.ToPtr())
}

// NewApprovals sets the approvals field to a newly
// allocated Artifact_Approval_List, preferring placement in s's segment.
func (s Artifact) NewApprovals(n int32) (Artifact_Approval_List, error) {
	l, err := NewArtifact_Approval_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Artifact_Approval_List{}, err
	}
	err = capnp.Struct(s).SetPtr(13, l.ToPtr())
	return l, err
}
func (s Artifact) Signature() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(14)
	return []byte(p.Data()), err
}

func (s Artifact) HasSignature() bool {
	return capnp.Struct(s).HasPtr(14)
}

func (s Artifact) SetSignature(v []byte) error {
	return capnp.Struct(s).SetData(14, v)
}

// Artifact_List is a list of Artifact.
type Artifact_List = capnp.StructList[Artifact]

// NewArtifact creates a new list of Artifact.
func NewArtifact_List(s *capnp.Segment, sz int32) (Artifact_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 15}, sz)
	return capnp.StructList[Artifact](l), err
}

// Artifact_Future is a wrapper for a Artifact promised by a client call.
type Artifact_Future struct{ *capnp.Future }

func (f Artifact_Future) Struct() (Artifact, error) {
	p, err := f.Future.Ptr()
	return Artifact(p.Struct()), err
}
func (p Artifact_Future) Error() Artifact_Error_Future {
	return Artifact_Error_Future{Future: p.Future.Field(2, nil)}
}

type Artifact_Error capnp.Struct

// Artifact_Error_TypeID is the unique identifier for the type Artifact_Error.
const Artifact_Error_TypeID = 0xb6507620d585d9aa

func NewArtifact_Error(s *capnp.Segment) (Artifact_Error, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return Artifact_Error(st), err
}

func NewRootArtifact_Error(s *capnp.Segment) (Artifact_Error, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return Artifact_Error(st), err
}

func ReadRootArtifact_Error(msg *capnp.Message) (Artifact_Error, error) {
	root, err := msg.Root()
	return Artifact_Error(root.Struct()), err
}

func (s Artifact_Error) String() string {
	str, _ := text.Marshal(0xb6507620d585d9aa, capnp.Struct(s))
	return str
}

func (s Artifact_Error) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Artifact_Error) DecodeFromPtr(p capnp.Ptr) Artifact_Error {
	return Artifact_Error(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Artifact_Error) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Artifact_Error) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Artifact_Error) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Artifact_Error) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Artifact_Error) Type() Artifact_Error_Type {
	return Artifact_Error_Type(capnp.Struct(s).Uint16(0))
}

func (s Artifact_Error) SetType(v Artifact_Error_Type) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s Artifact_Error) Timestamp() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s Artifact_Error) SetTimestamp(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s Artifact_Error) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Artifact_Error) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Artifact_Error) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Artifact_Error) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Artifact_Error_List is a list of Artifact_Error.
type Artifact_Error_List = capnp.StructList[Artifact_Error]

// NewArtifact_Error creates a new list of Artifact_Error.
func NewArtifact_Error_List(s *capnp.Segment, sz int32) (Artifact_Error_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[Artifact_Error](l), err
}

// Artifact_Error_Future is a wrapper for a Artifact_Error promised by a client call.
type Artifact_Error_Future struct{ *capnp.Future }

func (f Artifact_Error_Future) Struct() (Artifact_Error, error) {
	p, err := f.Future.Ptr()
	return Artifact_Error(p.Struct()), err
}

type Artifact_Error_Type uint16

// Artifact_Error_Type_TypeID is the unique identifier for the type Artifact_Error_Type.
const Artifact_Error_Type_TypeID = 0xe35eff8ed54464f6

// Values of Artifact_Error_Type.
const (
	Artifact_Error_Type_unknown    Artifact_Error_Type = 0
	Artifact_Error_Type_validation Artifact_Error_Type = 1
)

// String returns the enum's constant name.
func (c Artifact_Error_Type) String() string {
	switch c {
	case Artifact_Error_Type_unknown:
		return "unknown"
	case Artifact_Error_Type_validation:
		return "validation"

	default:
		return ""
	}
}

// Artifact_Error_TypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func Artifact_Error_TypeFromString(c string) Artifact_Error_Type {
	switch c {
	case "unknown":
		return Artifact_Error_Type_unknown
	case "validation":
		return Artifact_Error_Type_validation

	default:
		return 0
	}
}

type Artifact_Error_Type_List = capnp.EnumList[Artifact_Error_Type]

func NewArtifact_Error_Type_List(s *capnp.Segment, sz int32) (Artifact_Error_Type_List, error) {
	return capnp.NewEnumList[Artifact_Error_Type](s, sz)
}

type Artifact_Type uint16

// Artifact_Type_TypeID is the unique identifier for the type Artifact_Type.
const Artifact_Type_TypeID = 0xbbc6975bdbf2ac03

// Values of Artifact_Type.
const (
	Artifact_Type_json      Artifact_Type = 0
	Artifact_Type_artifact  Artifact_Type = 1
	Artifact_Type_artifacts Artifact_Type = 2
)

// String returns the enum's constant name.
func (c Artifact_Type) String() string {
	switch c {
	case Artifact_Type_json:
		return "json"
	case Artifact_Type_artifact:
		return "artifact"
	case Artifact_Type_artifacts:
		return "artifacts"

	default:
		return ""
	}
}

// Artifact_TypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func Artifact_TypeFromString(c string) Artifact_Type {
	switch c {
	case "json":
		return Artifact_Type_json
	case "artifact":
		return Artifact_Type_artifact
	case "artifacts":
		return Artifact_Type_artifacts

	default:
		return 0
	}
}

type Artifact_Type_List = capnp.EnumList[Artifact_Type]

func NewArtifact_Type_List(s *capnp.Segment, sz int32) (Artifact_Type_List, error) {
	return capnp.NewEnumList[Artifact_Type](s, sz)
}

type Artifact_Attribute capnp.Struct
type Artifact_Attribute_value Artifact_Attribute
type Artifact_Attribute_value_Which uint16

const (
	Artifact_Attribute_value_Which_textValue   Artifact_Attribute_value_Which = 0
	Artifact_Attribute_value_Which_intValue    Artifact_Attribute_value_Which = 1
	Artifact_Attribute_value_Which_floatValue  Artifact_Attribute_value_Which = 2
	Artifact_Attribute_value_Which_boolValue   Artifact_Attribute_value_Which = 3
	Artifact_Attribute_value_Which_binaryValue Artifact_Attribute_value_Which = 4
)

func (w Artifact_Attribute_value_Which) String() string {
	const s = "textValueintValuefloatValueboolValuebinaryValue"
	switch w {
	case Artifact_Attribute_value_Which_textValue:
		return s[0:9]
	case Artifact_Attribute_value_Which_intValue:
		return s[9:17]
	case Artifact_Attribute_value_Which_floatValue:
		return s[17:27]
	case Artifact_Attribute_value_Which_boolValue:
		return s[27:36]
	case Artifact_Attribute_value_Which_binaryValue:
		return s[36:47]

	}
	return "Artifact_Attribute_value_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Artifact_Attribute_TypeID is the unique identifier for the type Artifact_Attribute.
const Artifact_Attribute_TypeID = 0xe5ef7577388ccd38

func NewArtifact_Attribute(s *capnp.Segment) (Artifact_Attribute, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return Artifact_Attribute(st), err
}

func NewRootArtifact_Attribute(s *capnp.Segment) (Artifact_Attribute, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return Artifact_Attribute(st), err
}

func ReadRootArtifact_Attribute(msg *capnp.Message) (Artifact_Attribute, error) {
	root, err := msg.Root()
	return Artifact_Attribute(root.Struct()), err
}

func (s Artifact_Attribute) String() string {
	str, _ := text.Marshal(0xe5ef7577388ccd38, capnp.Struct(s))
	return str
}

func (s Artifact_Attribute) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Artifact_Attribute) DecodeFromPtr(p capnp.Ptr) Artifact_Attribute {
	return Artifact_Attribute(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Artifact_Attribute) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Artifact_Attribute) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Artifact_Attribute) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Artifact_Attribute) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Artifact_Attribute) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Artifact_Attribute) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Artifact_Attribute) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Artifact_Attribute) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Artifact_Attribute) Value() Artifact_Attribute_value { return Artifact_Attribute_value(s) }

func (s Artifact_Attribute_value) Which() Artifact_Attribute_value_Which {
	return Artifact_Attribute_value_Which(capnp.Struct(s).Uint16(0))
}
func (s Artifact_Attribute_value) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Artifact_Attribute_value) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Artifact_Attribute_value) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Artifact_Attribute_value) TextValue() (string, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != textValue")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Artifact_Attribute_value) HasTextValue() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s Artifact_Attribute_value) TextValueBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Artifact_Attribute_value) SetTextValue(v string) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetText(1, v)
}

func (s Artifact_Attribute_value) IntValue() int64 {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != intValue")
	}
	return int64(capnp.Struct(s).Uint64(8))
}

func (s Artifact_Attribute_value) SetIntValue(v int64) {
	capnp.Struct(s).SetUint16(0, 1)
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s Artifact_Attribute_value) FloatValue() float64 {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != floatValue")
	}
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Artifact_Attribute_value) SetFloatValue(v float64) {
	capnp.Struct(s).SetUint16(0, 2)
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s Artifact_Attribute_value) BoolValue() bool {
	if capnp.Struct(s).Uint16(0) != 3 {
		panic("Which() != boolValue")
	}
	return capnp.Struct(s).Bit(64)
}

func (s Artifact_Attribute_value) SetBoolValue(v bool) {
	capnp.Struct(s).SetUint16(0, 3)
	capnp.Struct(s).SetBit(64, v)
}

func (s Artifact_Attribute_value) BinaryValue() ([]byte, error) {
	if capnp.Struct(s).Uint16(0) != 4 {
		panic("Which() != binaryValue")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s Artifact_Attribute_value) HasBinaryValue() bool {
	if capnp.Struct(s).Uint16(0) != 4 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s Artifact_Attribute_value) SetBinaryValue(v []byte) error {
	capnp.Struct(s).SetUint16(0, 4)
	return capnp.Struct(s).SetData(1, v)
}

// Artifact_Attribute_List is a list of Artifact_Attribute.
type Artifact_Attribute_List = capnp.StructList[Artifact_Attribute]

// NewArtifact_Attribute creates a new list of Artifact_Attribute.
func NewArtifact_Attribute_List(s *capnp.Segment, sz int32) (Artifact_Attribute_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2}, sz)
	return capnp.StructList[Artifact_Attribute](l), err
}

// Artifact_Attribute_Future is a wrapper for a Artifact_Attribute promised by a client call.
type Artifact_Attribute_Future struct{ *capnp.Future }

func (f Artifact_Attribute_Future) Struct() (Artifact_Attribute, error) {
	p, err := f.Future.Ptr()
	return Artifact_Attribute(p.Struct()), err
}
func (p Artifact_Attribute_Future) Value() Artifact_Attribute_value_Future {
	return Artifact_Attribute_value_Future{p.Future}
}

// Artifact_Attribute_value_Future is a wrapper for a Artifact_Attribute_value promised by a client call.
type Artifact_Attribute_value_Future struct{ *capnp.Future }

func (f Artifact_Attribute_value_Future) Struct() (Artifact_Attribute_value, error) {
	p, err := f.Future.Ptr()
	return Artifact_Attribute_value(p.Struct()), err
}

type Artifact_Approval capnp.Struct

// Artifact_Approval_TypeID is the unique identifier for the type Artifact_Approval.
const Artifact_Approval_TypeID = 0x8cc20228b0f1020d

func NewArtifact_Approval(s *capnp.Segment) (Artifact_Approval, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Artifact_Approval(st), err
}

func NewRootArtifact_Approval(s *capnp.Segment) (Artifact_Approval, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Artifact_Approval(st), err
}

func ReadRootArtifact_Approval(msg *capnp.Message) (Artifact_Approval, error) {
	root, err := msg.Root()
	return Artifact_Approval(root.Struct()), err
}

func (s Artifact_Approval) String() string {
	str, _ := text.Marshal(0x8cc20228b0f1020d, capnp.Struct(s))
	return str
}

func (s Artifact_Approval) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Artifact_Approval) DecodeFromPtr(p capnp.Ptr) Artifact_Approval {
	return Artifact_Approval(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Artifact_Approval) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Artifact_Approval) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Artifact_Approval) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Artifact_Approval) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Artifact_Approval) ZkProof() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Artifact_Approval) HasZkProof() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Artifact_Approval) SetZkProof(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Artifact_Approval) OperatorBlindSignature() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s Artifact_Approval) HasOperatorBlindSignature() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Artifact_Approval) SetOperatorBlindSignature(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// Artifact_Approval_List is a list of Artifact_Approval.
type Artifact_Approval_List = capnp.StructList[Artifact_Approval]

// NewArtifact_Approval creates a new list of Artifact_Approval.
func NewArtifact_Approval_List(s *capnp.Segment, sz int32) (Artifact_Approval_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Artifact_Approval](l), err
}

// Artifact_Approval_Future is a wrapper for a Artifact_Approval promised by a client call.
type Artifact_Approval_Future struct{ *capnp.Future }

func (f Artifact_Approval_Future) Struct() (Artifact_Approval, error) {
	p, err := f.Future.Ptr()
	return Artifact_Approval(p.Struct()), err
}

const schema_85d3acc39d94e0f8 = "x\xda\x84\x95oh\x1cU\x17\xc6\x9f\xe7\xde\xdd\xec&" +
	"\xd9\xcdf\xde\xd9\xf2\xf6}1F\x8aB\x8d6\xa4\x8d" +
	"`-\x95\xb6\xa1\xc1\x9a\x16\xcc\xcd\xd4\"\xf5\x0fN\xb2" +
	"\x93d\x9a\xcd\xce:;\x93\xb8\xa2\xf4\x8b\x05\x95*\x8a" +
	"-\x8a\xb4\xe0\x17Q\xa4\xfe\xfb\"\xa8\x88XE\xfd\x12" +
	"\xb4h\xc1b\x05\xc5\x06D\xac\xd6\xe2\x9f\x8a\xad#w" +
	"\xd2\x9d][\x8b\xf9\x94\xfd\xcd\x99s\xce<\xf79\xe7" +
	"\x0e\x1c\x10\x1bS\xab\xf3\x1fK\x08um\xba-\xca\x8b" +
	"\x9f^])\x0e\xef\x85\xb1\x9c\xbf-\x86/w]\xd3" +
	"\xfeZZd\x80\xc1\x05v\xd0\xfc\x92\x19\xc0<\xc6y" +
	"0z\xf2\xfd\xc9\xec\xdc\x0f\x1f>\x0f\xb5\x82\"Z\xbb" +
	"\xb0w\xed|\xf8\xe3\"n\x15\x19\xa6\x81\xc1\x1b\xc5\x10" +
	"\xc1\xc1a\xd1K$\xa9T\x81\":\xf3\xd5\xbe\x83\xef" +
	"\x1d\xfat\x0f\xd2\x05\x9d\xcd\x95\x87\xcd{\xe4M\xc0\xe0" +
	"s\xf2\x1d\x09F/\x1e\xdbs\xf4\x8a\xb9\xd1\xd7\xa1\x96" +
	"S$M,U\xce\x9c6\x173\xff\x05\xcc\x93\x99W" +
	"\xc0H\x1e:\xfd\xc5\xedO}\xf0\x16\x8c\xe5I$h" +
	">\x9c\xfd\xce\xdc\x9f\xd5/<\x91\xbd\x05\x8c~-m" +
	">\xfaXt\xd770.\x17\xcd\xf4\xe0\xe0K\xd9\xff" +
	"\xd3|;\x8e|#{=\xd8\xfc\x8c\xbf\xd5\x8e\x05x" +
	"7\xfb\x1f\x9aG\xe2\xd8\x85\xec<VE\xb6\x1f\xb8\x93" +
	"\xf6D \xfb'\xecj\xa5\xban\xd3\xf9\xdf\xfd\x9b\xaa" +
	"U\xdf\x9b\xb3\xcb\xc0(\xa9\xb22\x05\xa4\x08\x18W\x0f" +
	"\x01\xeaJI5 h\x90Ej\xb8\xeaM@\x0dH" +
	"\xaa\xf5\x82\xbb\xef\x9b\x19\xf5=o\x92y\x08\xe6\xc1\xc8" +
	"\xab:\xbe\x1dx>\x87\xcan\xa5d\xb9S\x1b*v" +
	"\x10\xfaN\x12\xd0\xe8!uQ\x0fA\xe0\xbb\xe3a\xe0" +
	"\xf4\xcf\xd9\xe5\xd0\x81*\xca\xd4eQt\xbe\xe8\x03c" +
	"\x80\xba_R=$\xd8\xc3?5\x16\x80\xb1g\x04P" +
	"\x0fJ\xaa\xc7\x05{\xc49\x8d%`<\xba\x13P{" +
	"%\xd5\xd3\x82=\xf2l\xb4\xb1\xc8\x14`\xec\xd7I\xf6" +
	"I\xaag\x05{R\x7f\xe8\xe84`\x1c\x1c\x07\xd4\x01" +
	"I\xf5\x82`\x148\xf7\x06;\xecr\x08:\xccA0" +
	"\x07Fn%F\x0e\x00\xa6!\x98\x06\xa3\xc9\xb2gk" +
	"\x0a\x19:\xec\x84`'\x18\x8d{^\xb9\xf12!H" +
	"\xcd\xdc\x8a\xed\xd7w\xd8\xc8\x94\xc3\x8be\x10\x17\xc8\x00" +
	"\xd5\xcd\x16C\x19\xff[\xd3b\x99e}\xcd\xe36\x8c" +
	"\xb1\x16\xef\x1b#\xbd\xc3\xbe\xef\xf9\x85\xed\xf5\xaa\x135" +
	"\xa4\x04\x9d\xa8y\xb4P\x9b\x1b\x07k.\xb0\x0f\xb0>" +
	"\xa2\xa4\xf5\x19\x9bgk\x1e\xe1\x08`}\xa2\xf9q\x0a" +
	"R\xc42\x9b\xc78\x06X\x9fk|B\x87K\x11\xeb" +
	"l~\xcd5\x80u\\\xf3o5O\xc9Xhs\x91" +
	">`\x9d\xd0\xfc\x94\xe6\xe9T\xac\xb4y\x92;\x01\xeb" +
	"{\xcd\xcfh\xde\x96*\xb2\x0d0\x7f\x89\xdb9\xa5\xf9" +
	"Y\xcd3\xe9b<=\xbfs\x1d`\xfdL\xc91!" +
	"hd\xdb\x8a\xcc\x02\xe69\x8e\x03\xd6Y\x1d\x9e\xd5\xbc" +
	"=Sd;`\xa6E\x1f0&$\xad\x9c\xc6\x1d\xd9" +
	"\";\x00\xb3]\xe8.S\x9awk\xde\xd9^d'" +
	"`\xe6\x85\xee&\xa7\xf9J\xcds\x1dE\xe6\x00\xf3*" +
	"\xf1\x08`\xad\xd4\xfc:\xcd\xf3\x9dE\xe6\x01s\xb5\xd8" +
	"\x05X\x03\x9a\xaf\xd7\xbc+Wd\x17`\xde \x9e\x01" +
	"\xac\xf5\x9ao\xd1\xbc\x90/\xb2\x00\x98\xc3B\xab\xb6Y" +
	"\xf3\xbb5\xef\xee*\xb2\x1b0\xef\x8c\xf9\x1d\x9aO\x0b" +
	"\xc1B\x18\xba\xa5\xc4\x18\x13\xd3\xce\xc4L-\x9c\xd5^" +
	"k\xb0\xc0\x9duj\x81=\x0bV\x1b\xfe\xebu\xf4q" +
	"\xb3\xbbu9\xb0\x1b\x8c\xaa5',y\x95:zg" +
	"\xb7\xd8\xb5\xe9$\xc7\xac\xe3\xcf\x94\x9d1\x0f\xd2\x0b\x1a" +
	"\xb0\x10\xd4\xab\x0e\x0bM\x87\x81,\x80\x1b<\xdf\x9dr" +
	"+\x89\xfdKN-p+v\x80\x8c\xeb%\xb4\xe0{" +
	"\xe5dBzk\x13^\xb59/v\xc3\x7f\xd2\xa9\xb1" +
	"\x0b\x1c\x95dw\xd3\xba\xa0\x86\x91S\x99\xf0\xeb\xd5\xc0" +
	"ai\xd4\xae\x97=\xbb\xd4\xf2\xc5\x8dg(\x94\xb6:" +
	"\xf5&\xaeN;\xb3\x8eo\xb3<\x1a\x8e\x97\xdd\x89\xad" +
	"\xb2\xe5\xa1\xddp:[\x8a&#r\xbeh\xcd\x9d\x8a" +
	"\x17\x92\x9e\xd0\x7f\x9b\xc5\xfe\xa5\x99R)\xb6.d\xf6" +
	"\xc5C\xa6r\xc9\x96\x1c\xee\x03\xd4FI\xb5\xadeK" +
	"\xde\xacw\xcd\x16I\xb5=\x19#C\xe9u\xbaMR" +
	"\xdd&\x12\xed\x93\xc4K\xda\xff\xd3Y\xef\x9euj5" +
	"{\xaaE\xdfK5\x1cw\xa6Wx.\xae\xd7\xd3\xa7" +
	"\xb3\x1a\xcbF\x00\x0a\xc3\x18\x03\x0a\xbbj^%y\x1f" +
	"@\xf3\x7f\xd6.}?\xc4:\xf4o\xaf\xcb\xa5\xec\xd9" +
	"8\xbb1\x14go\xdf\x09\xec\x0e+3\x15o\xbe\x12" +
	"\xcd\xd9e\xb7d\x07.dK\x19y\xa9UO\xe7\x82" +
	"\xebfE\xf3\xba\xd1\x7f\xcd\x1b\xdbX\xb5\x06\"3\xe3" +
	"\xd4\x13\xc7\xc5\x97\xc4_\x01\x00\x00\xff\xff\xd3i\xfez"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_85d3acc39d94e0f8,
		Nodes: []uint64{
			0x8cc20228b0f1020d,
			0xa7c7ee760866c493,
			0xb1092b0e00ae75e5,
			0xb6507620d585d9aa,
			0xbbc6975bdbf2ac03,
			0xe35eff8ed54464f6,
			0xe5ef7577388ccd38,
		},
		Compressed: true,
	})
}
