// Code generated by capnpc-go. DO NOT EDIT.

package datura

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
	strconv "strconv"
)

type Artifact capnp.Struct

// Artifact_TypeID is the unique identifier for the type Artifact.
const Artifact_TypeID = 0xb1092b0e00ae75e5

func NewArtifact(s *capnp.Segment) (Artifact, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 15})
	return Artifact(st), err
}

func NewRootArtifact(s *capnp.Segment) (Artifact, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 15})
	return Artifact(st), err
}

func ReadRootArtifact(msg *capnp.Message) (Artifact, error) {
	root, err := msg.Root()
	return Artifact(root.Struct()), err
}

func (s Artifact) String() string {
	str, _ := text.Marshal(0xb1092b0e00ae75e5, capnp.Struct(s))
	return str
}

func (s Artifact) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Artifact) DecodeFromPtr(p capnp.Ptr) Artifact {
	return Artifact(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Artifact) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Artifact) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Artifact) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Artifact) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Artifact) Uuid() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Artifact) HasUuid() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Artifact) SetUuid(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Artifact) Checksum() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s Artifact) HasChecksum() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Artifact) SetChecksum(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

func (s Artifact) Timestamp() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s Artifact) SetTimestamp(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s Artifact) Error() (Artifact_Error, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return Artifact_Error(p.Struct()), err
}

func (s Artifact) HasError() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Artifact) SetError(v Artifact_Error) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewError sets the error field to a newly
// allocated Artifact_Error struct, preferring placement in s's segment.
func (s Artifact) NewError() (Artifact_Error, error) {
	ss, err := NewArtifact_Error(capnp.Struct(s).Segment())
	if err != nil {
		return Artifact_Error{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Artifact) PseudonymHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return []byte(p.Data()), err
}

func (s Artifact) HasPseudonymHash() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Artifact) SetPseudonymHash(v []byte) error {
	return capnp.Struct(s).SetData(3, v)
}

func (s Artifact) MerkleRoot() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return []byte(p.Data()), err
}

func (s Artifact) HasMerkleRoot() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Artifact) SetMerkleRoot(v []byte) error {
	return capnp.Struct(s).SetData(4, v)
}

func (s Artifact) Type() Artifact_Type {
	return Artifact_Type(capnp.Struct(s).Uint16(8))
}

func (s Artifact) SetType(v Artifact_Type) {
	capnp.Struct(s).SetUint16(8, uint16(v))
}

func (s Artifact) Origin() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s Artifact) HasOrigin() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Artifact) OriginBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s Artifact) SetOrigin(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s Artifact) Destination() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s Artifact) HasDestination() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s Artifact) DestinationBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s Artifact) SetDestination(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s Artifact) Role() (string, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.Text(), err
}

func (s Artifact) HasRole() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s Artifact) RoleBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.TextBytes(), err
}

func (s Artifact) SetRole(v string) error {
	return capnp.Struct(s).SetText(7, v)
}

func (s Artifact) Scope() (string, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.Text(), err
}

func (s Artifact) HasScope() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s Artifact) ScopeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.TextBytes(), err
}

func (s Artifact) SetScope(v string) error {
	return capnp.Struct(s).SetText(8, v)
}

func (s Artifact) Attributes() (Artifact_Attribute_List, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return Artifact_Attribute_List(p.List()), err
}

func (s Artifact) HasAttributes() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s Artifact) SetAttributes(v Artifact_Attribute_List) error {
	return capnp.Struct(s).SetPtr(9, v.ToPtr())
}

// NewAttributes sets the attributes field to a newly
// allocated Artifact_Attribute_List, preferring placement in s's segment.
func (s Artifact) NewAttributes(n int32) (Artifact_Attribute_List, error) {
	l, err := NewArtifact_Attribute_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Artifact_Attribute_List{}, err
	}
	err = capnp.Struct(s).SetPtr(9, l.ToPtr())
	return l, err
}
func (s Artifact) EncryptedPayload() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return []byte(p.Data()), err
}

func (s Artifact) HasEncryptedPayload() bool {
	return capnp.Struct(s).HasPtr(10)
}

func (s Artifact) SetEncryptedPayload(v []byte) error {
	return capnp.Struct(s).SetData(10, v)
}

func (s Artifact) EncryptedKey() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(11)
	return []byte(p.Data()), err
}

func (s Artifact) HasEncryptedKey() bool {
	return capnp.Struct(s).HasPtr(11)
}

func (s Artifact) SetEncryptedKey(v []byte) error {
	return capnp.Struct(s).SetData(11, v)
}

func (s Artifact) EphemeralPublicKey() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(12)
	return []byte(p.Data()), err
}

func (s Artifact) HasEphemeralPublicKey() bool {
	return capnp.Struct(s).HasPtr(12)
}

func (s Artifact) SetEphemeralPublicKey(v []byte) error {
	return capnp.Struct(s).SetData(12, v)
}

func (s Artifact) Approvals() (Artifact_Approval_List, error) {
	p, err := capnp.Struct(s).Ptr(13)
	return Artifact_Approval_List(p.List()), err
}

func (s Artifact) HasApprovals() bool {
	return capnp.Struct(s).HasPtr(13)
}

func (s Artifact) SetApprovals(v Artifact_Approval_List) error {
	return capnp.Struct(s).SetPtr(13, v.ToPtr())
}

// NewApprovals sets the approvals field to a newly
// allocated Artifact_Approval_List, preferring placement in s's segment.
func (s Artifact) NewApprovals(n int32) (Artifact_Approval_List, error) {
	l, err := NewArtifact_Approval_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Artifact_Approval_List{}, err
	}
	err = capnp.Struct(s).SetPtr(13, l.ToPtr())
	return l, err
}
func (s Artifact) Signature() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(14)
	return []byte(p.Data()), err
}

func (s Artifact) HasSignature() bool {
	return capnp.Struct(s).HasPtr(14)
}

func (s Artifact) SetSignature(v []byte) error {
	return capnp.Struct(s).SetData(14, v)
}

// Artifact_List is a list of Artifact.
type Artifact_List = capnp.StructList[Artifact]

// NewArtifact creates a new list of Artifact.
func NewArtifact_List(s *capnp.Segment, sz int32) (Artifact_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 15}, sz)
	return capnp.StructList[Artifact](l), err
}

// Artifact_Future is a wrapper for a Artifact promised by a client call.
type Artifact_Future struct{ *capnp.Future }

func (f Artifact_Future) Struct() (Artifact, error) {
	p, err := f.Future.Ptr()
	return Artifact(p.Struct()), err
}
func (p Artifact_Future) Error() Artifact_Error_Future {
	return Artifact_Error_Future{Future: p.Future.Field(2, nil)}
}

type Artifact_Error capnp.Struct

// Artifact_Error_TypeID is the unique identifier for the type Artifact_Error.
const Artifact_Error_TypeID = 0xb6507620d585d9aa

func NewArtifact_Error(s *capnp.Segment) (Artifact_Error, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return Artifact_Error(st), err
}

func NewRootArtifact_Error(s *capnp.Segment) (Artifact_Error, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return Artifact_Error(st), err
}

func ReadRootArtifact_Error(msg *capnp.Message) (Artifact_Error, error) {
	root, err := msg.Root()
	return Artifact_Error(root.Struct()), err
}

func (s Artifact_Error) String() string {
	str, _ := text.Marshal(0xb6507620d585d9aa, capnp.Struct(s))
	return str
}

func (s Artifact_Error) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Artifact_Error) DecodeFromPtr(p capnp.Ptr) Artifact_Error {
	return Artifact_Error(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Artifact_Error) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Artifact_Error) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Artifact_Error) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Artifact_Error) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Artifact_Error) Type() Artifact_Error_Type {
	return Artifact_Error_Type(capnp.Struct(s).Uint16(0))
}

func (s Artifact_Error) SetType(v Artifact_Error_Type) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s Artifact_Error) Timestamp() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s Artifact_Error) SetTimestamp(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s Artifact_Error) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Artifact_Error) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Artifact_Error) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Artifact_Error) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Artifact_Error_List is a list of Artifact_Error.
type Artifact_Error_List = capnp.StructList[Artifact_Error]

// NewArtifact_Error creates a new list of Artifact_Error.
func NewArtifact_Error_List(s *capnp.Segment, sz int32) (Artifact_Error_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[Artifact_Error](l), err
}

// Artifact_Error_Future is a wrapper for a Artifact_Error promised by a client call.
type Artifact_Error_Future struct{ *capnp.Future }

func (f Artifact_Error_Future) Struct() (Artifact_Error, error) {
	p, err := f.Future.Ptr()
	return Artifact_Error(p.Struct()), err
}

type Artifact_Error_Type uint16

// Artifact_Error_Type_TypeID is the unique identifier for the type Artifact_Error_Type.
const Artifact_Error_Type_TypeID = 0xe35eff8ed54464f6

// Values of Artifact_Error_Type.
const (
	Artifact_Error_Type_unknown    Artifact_Error_Type = 0
	Artifact_Error_Type_validation Artifact_Error_Type = 1
)

// String returns the enum's constant name.
func (c Artifact_Error_Type) String() string {
	switch c {
	case Artifact_Error_Type_unknown:
		return "unknown"
	case Artifact_Error_Type_validation:
		return "validation"

	default:
		return ""
	}
}

// Artifact_Error_TypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func Artifact_Error_TypeFromString(c string) Artifact_Error_Type {
	switch c {
	case "unknown":
		return Artifact_Error_Type_unknown
	case "validation":
		return Artifact_Error_Type_validation

	default:
		return 0
	}
}

type Artifact_Error_Type_List = capnp.EnumList[Artifact_Error_Type]

func NewArtifact_Error_Type_List(s *capnp.Segment, sz int32) (Artifact_Error_Type_List, error) {
	return capnp.NewEnumList[Artifact_Error_Type](s, sz)
}

type Artifact_Type uint16

// Artifact_Type_TypeID is the unique identifier for the type Artifact_Type.
const Artifact_Type_TypeID = 0xbbc6975bdbf2ac03

// Values of Artifact_Type.
const (
	Artifact_Type_json      Artifact_Type = 0
	Artifact_Type_artifact  Artifact_Type = 1
	Artifact_Type_artifacts Artifact_Type = 2
)

// String returns the enum's constant name.
func (c Artifact_Type) String() string {
	switch c {
	case Artifact_Type_json:
		return "json"
	case Artifact_Type_artifact:
		return "artifact"
	case Artifact_Type_artifacts:
		return "artifacts"

	default:
		return ""
	}
}

// Artifact_TypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func Artifact_TypeFromString(c string) Artifact_Type {
	switch c {
	case "json":
		return Artifact_Type_json
	case "artifact":
		return Artifact_Type_artifact
	case "artifacts":
		return Artifact_Type_artifacts

	default:
		return 0
	}
}

type Artifact_Type_List = capnp.EnumList[Artifact_Type]

func NewArtifact_Type_List(s *capnp.Segment, sz int32) (Artifact_Type_List, error) {
	return capnp.NewEnumList[Artifact_Type](s, sz)
}

type Artifact_Attribute capnp.Struct
type Artifact_Attribute_value Artifact_Attribute
type Artifact_Attribute_value_Which uint16

const (
	Artifact_Attribute_value_Which_textValue   Artifact_Attribute_value_Which = 0
	Artifact_Attribute_value_Which_intValue    Artifact_Attribute_value_Which = 1
	Artifact_Attribute_value_Which_floatValue  Artifact_Attribute_value_Which = 2
	Artifact_Attribute_value_Which_floatValues Artifact_Attribute_value_Which = 3
	Artifact_Attribute_value_Which_boolValue   Artifact_Attribute_value_Which = 4
	Artifact_Attribute_value_Which_binaryValue Artifact_Attribute_value_Which = 5
)

func (w Artifact_Attribute_value_Which) String() string {
	const s = "textValueintValuefloatValuefloatValuesboolValuebinaryValue"
	switch w {
	case Artifact_Attribute_value_Which_textValue:
		return s[0:9]
	case Artifact_Attribute_value_Which_intValue:
		return s[9:17]
	case Artifact_Attribute_value_Which_floatValue:
		return s[17:27]
	case Artifact_Attribute_value_Which_floatValues:
		return s[27:38]
	case Artifact_Attribute_value_Which_boolValue:
		return s[38:47]
	case Artifact_Attribute_value_Which_binaryValue:
		return s[47:58]

	}
	return "Artifact_Attribute_value_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Artifact_Attribute_TypeID is the unique identifier for the type Artifact_Attribute.
const Artifact_Attribute_TypeID = 0xe5ef7577388ccd38

func NewArtifact_Attribute(s *capnp.Segment) (Artifact_Attribute, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return Artifact_Attribute(st), err
}

func NewRootArtifact_Attribute(s *capnp.Segment) (Artifact_Attribute, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return Artifact_Attribute(st), err
}

func ReadRootArtifact_Attribute(msg *capnp.Message) (Artifact_Attribute, error) {
	root, err := msg.Root()
	return Artifact_Attribute(root.Struct()), err
}

func (s Artifact_Attribute) String() string {
	str, _ := text.Marshal(0xe5ef7577388ccd38, capnp.Struct(s))
	return str
}

func (s Artifact_Attribute) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Artifact_Attribute) DecodeFromPtr(p capnp.Ptr) Artifact_Attribute {
	return Artifact_Attribute(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Artifact_Attribute) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Artifact_Attribute) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Artifact_Attribute) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Artifact_Attribute) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Artifact_Attribute) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Artifact_Attribute) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Artifact_Attribute) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Artifact_Attribute) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Artifact_Attribute) Value() Artifact_Attribute_value { return Artifact_Attribute_value(s) }

func (s Artifact_Attribute_value) Which() Artifact_Attribute_value_Which {
	return Artifact_Attribute_value_Which(capnp.Struct(s).Uint16(0))
}
func (s Artifact_Attribute_value) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Artifact_Attribute_value) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Artifact_Attribute_value) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Artifact_Attribute_value) TextValue() (string, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != textValue")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Artifact_Attribute_value) HasTextValue() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s Artifact_Attribute_value) TextValueBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Artifact_Attribute_value) SetTextValue(v string) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetText(1, v)
}

func (s Artifact_Attribute_value) IntValue() int64 {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != intValue")
	}
	return int64(capnp.Struct(s).Uint64(8))
}

func (s Artifact_Attribute_value) SetIntValue(v int64) {
	capnp.Struct(s).SetUint16(0, 1)
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s Artifact_Attribute_value) FloatValue() float64 {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != floatValue")
	}
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Artifact_Attribute_value) SetFloatValue(v float64) {
	capnp.Struct(s).SetUint16(0, 2)
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s Artifact_Attribute_value) FloatValues() (capnp.Float64List, error) {
	if capnp.Struct(s).Uint16(0) != 3 {
		panic("Which() != floatValues")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.Float64List(p.List()), err
}

func (s Artifact_Attribute_value) HasFloatValues() bool {
	if capnp.Struct(s).Uint16(0) != 3 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s Artifact_Attribute_value) SetFloatValues(v capnp.Float64List) error {
	capnp.Struct(s).SetUint16(0, 3)
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewFloatValues sets the floatValues field to a newly
// allocated capnp.Float64List, preferring placement in s's segment.
func (s Artifact_Attribute_value) NewFloatValues(n int32) (capnp.Float64List, error) {
	capnp.Struct(s).SetUint16(0, 3)
	l, err := capnp.NewFloat64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Float64List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s Artifact_Attribute_value) BoolValue() bool {
	if capnp.Struct(s).Uint16(0) != 4 {
		panic("Which() != boolValue")
	}
	return capnp.Struct(s).Bit(64)
}

func (s Artifact_Attribute_value) SetBoolValue(v bool) {
	capnp.Struct(s).SetUint16(0, 4)
	capnp.Struct(s).SetBit(64, v)
}

func (s Artifact_Attribute_value) BinaryValue() ([]byte, error) {
	if capnp.Struct(s).Uint16(0) != 5 {
		panic("Which() != binaryValue")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s Artifact_Attribute_value) HasBinaryValue() bool {
	if capnp.Struct(s).Uint16(0) != 5 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s Artifact_Attribute_value) SetBinaryValue(v []byte) error {
	capnp.Struct(s).SetUint16(0, 5)
	return capnp.Struct(s).SetData(1, v)
}

// Artifact_Attribute_List is a list of Artifact_Attribute.
type Artifact_Attribute_List = capnp.StructList[Artifact_Attribute]

// NewArtifact_Attribute creates a new list of Artifact_Attribute.
func NewArtifact_Attribute_List(s *capnp.Segment, sz int32) (Artifact_Attribute_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2}, sz)
	return capnp.StructList[Artifact_Attribute](l), err
}

// Artifact_Attribute_Future is a wrapper for a Artifact_Attribute promised by a client call.
type Artifact_Attribute_Future struct{ *capnp.Future }

func (f Artifact_Attribute_Future) Struct() (Artifact_Attribute, error) {
	p, err := f.Future.Ptr()
	return Artifact_Attribute(p.Struct()), err
}
func (p Artifact_Attribute_Future) Value() Artifact_Attribute_value_Future {
	return Artifact_Attribute_value_Future{p.Future}
}

// Artifact_Attribute_value_Future is a wrapper for a Artifact_Attribute_value promised by a client call.
type Artifact_Attribute_value_Future struct{ *capnp.Future }

func (f Artifact_Attribute_value_Future) Struct() (Artifact_Attribute_value, error) {
	p, err := f.Future.Ptr()
	return Artifact_Attribute_value(p.Struct()), err
}

type Artifact_Approval capnp.Struct

// Artifact_Approval_TypeID is the unique identifier for the type Artifact_Approval.
const Artifact_Approval_TypeID = 0x8cc20228b0f1020d

func NewArtifact_Approval(s *capnp.Segment) (Artifact_Approval, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Artifact_Approval(st), err
}

func NewRootArtifact_Approval(s *capnp.Segment) (Artifact_Approval, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Artifact_Approval(st), err
}

func ReadRootArtifact_Approval(msg *capnp.Message) (Artifact_Approval, error) {
	root, err := msg.Root()
	return Artifact_Approval(root.Struct()), err
}

func (s Artifact_Approval) String() string {
	str, _ := text.Marshal(0x8cc20228b0f1020d, capnp.Struct(s))
	return str
}

func (s Artifact_Approval) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Artifact_Approval) DecodeFromPtr(p capnp.Ptr) Artifact_Approval {
	return Artifact_Approval(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Artifact_Approval) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Artifact_Approval) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Artifact_Approval) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Artifact_Approval) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Artifact_Approval) ZkProof() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Artifact_Approval) HasZkProof() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Artifact_Approval) SetZkProof(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Artifact_Approval) OperatorBlindSignature() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s Artifact_Approval) HasOperatorBlindSignature() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Artifact_Approval) SetOperatorBlindSignature(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// Artifact_Approval_List is a list of Artifact_Approval.
type Artifact_Approval_List = capnp.StructList[Artifact_Approval]

// NewArtifact_Approval creates a new list of Artifact_Approval.
func NewArtifact_Approval_List(s *capnp.Segment, sz int32) (Artifact_Approval_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Artifact_Approval](l), err
}

// Artifact_Approval_Future is a wrapper for a Artifact_Approval promised by a client call.
type Artifact_Approval_Future struct{ *capnp.Future }

func (f Artifact_Approval_Future) Struct() (Artifact_Approval, error) {
	p, err := f.Future.Ptr()
	return Artifact_Approval(p.Struct()), err
}

const schema_85d3acc39d94e0f8 = "x\xda\x84\x95]h\x1c\xe5\x1a\xc7\xff\xff\xf7\xdd\xcd\xee" +
	"&\xbb\xd9\xcc\x99-'\xe7pr\xa2E\xa1\x8d6\xa4" +
	"\x8db--mC\x835-\x987[\xab\xd4\x0f\x9c" +
	"d'\xc94\xbb;\xcb\xecL\xe2z\xd3\xab\xdeH\xf1" +
	"F\xc1\x0f\x10\x14\x04?(\xda\x82\x08\xea\x85XE+" +
	"Xl\xb1\x05\x83\x15,6 \xe2G-V\xab\xb6\x8e" +
	"\xbc\xd3\xee\xec\xdaZ\xccU\xf67\xcf<\xef3\xcf\xf3" +
	"\xff?\xef\xd0\x01\xb1)\xb1:\xf7\x89\x84P7';" +
	"\xc2\x9c\xf8\xf1\xc0\x0aqh\x1f\x8c^\xfe\xb2\x14\xbc\xda" +
	"}S\xe6`R\xa4\x80\xe1#\xec\xa4\xf9\x05S\x80\xb9" +
	"\xc8\x050|\xfc\xfd\xe9\xf4\xfc\xf7\x1f\xbe\x08\xb5\x9c\"" +
	"\\{d\xdf\xda\x85\xe0\x87%\xdc-R\xec\x00\x867" +
	"\x88\x11\x82\xc3\xa3\xe2\x1e\"N\xa5\xf2\x14\xe1\xf9/\x9f" +
	"x\xf6\xbd\xfd\x9f\xeeE2\xaf\xb3\xbd)\x0f\x99\xef\xca" +
	";\x80\xe1s\xf2\x1d\x09\x86\xaf,\xee=q\xdd\xfc\xf8" +
	"\x1bP\xbd\x14q\x11\xd1\xc9+\xd3g\xcd[\xd3\xff\x06" +
	"\xcc\x0d\xe9\xd7\xc0P\xee?\xfb\xf9}O~\xf06\x8c" +
	"\xde8\x124\x17\xd3\xdf\x98Ki\xfd\xc2\xa9\xf4]`" +
	"\xf8si\xcb\x89\xc7\xc2\x07\xbf\x82\xf1\x7f\xd1J\x0f\x0e" +
	"_L\xff\x97f.\xa3#3\x99\xdb\xc0\xd6g\xfc\xe5" +
	"\xec\xa8\x01F\xe6_4\xaf\x8fb\xfb2\x0bX\x15Z" +
	"\x9e\xefL[S\xbe\x1c\x9c\xb2j\xd5\xda\xba\xcd\x97\x7f" +
	"\x0fn\xae\xd5<w\xde*\x03\xe3\xa4J\xcb\x04\x90 " +
	"`\xac\x1c\x01\xd4\x0d\x92jH\xd0 \x0b\xd4p\xd5[" +
	"\x80\x1a\x92T\xeb\x05\xf7<27\xee\xb9\xee4s\x10" +
	"\xcc\x81\xa1[\xb3=\xcbw=\x8e\x94\x9dj\xa9\xe8\xcc" +
	"l\xacZ~\xe0\xd9q@\xb3\x86\xc4U5\xf8\xbe\xe7" +
	"L\x06\xbe=8o\x95\x03\x1b\xaaW&\xfe\x17\x86\x97" +
	"\x0f}z\x02POI\xaa\x17\x04\xfb\xf8\x87\xc6\x020" +
	"\x9e\x1f\x03\xd4s\x92j\xbf`\x9f\xb8\xa8\xb1\x04\x8c\x97" +
	"w\x01\xea%I\xf5\xba`\x9f\xbc\xa0q\x020\x0eN" +
	"\x02\xea\x80\xa4\xfaX\xb0/\xf1{\xb8\xa9\xc0$`|" +
	"\xa4s\x1f\x96T\xc7\x05\xfb\x92\xbf\xe9\xe8\x0e\xc08\xa6" +
	"\xa3\x8fJ\xaa\x93\x82\xa1o?\xec\xef\xb4\xca\x01h3" +
	"\x0b\xc1,\x18:\xd5\x08\xd9\x00\x98\x84`\x12\x0c\xa7\xcb" +
	"\xae\xa5)d`\xb3\x0b\x82]\xed0\x15\xd8uv\x83" +
	"\xe3\x92\xd1\xc3n0\x9ct\xddr33!H\xcd\x9c" +
	"\xaa\xe55vZH\x95\x83\xab['\xaeh\x1dT\x0f" +
	"\xdbDh\xfcgM\x9b\xcc\x96\x0d\xb4$b\x18\x13m" +
	"~1\xc6\xfaG=\xcf\xf5\xf2;\x1a5;l\xb6\x1f" +
	"\xb4\xc3\x96\x1c\xa0\xb64\xc5`\x1e\xe1\x00P<L\xc9" +
	"\xe2q\xb6\xf4`\x1e\xe3\x18P<\xaa\xf9I\x0aRD" +
	"\xa31\x179\x01\x14?\xd3\xf8\xb4\x0e\x97\"\x9a\x8dy" +
	"\x8ak\x80\xe2I\xcd\xbf\xd6<!\xa3\xe1\x98K\xf4\x80" +
	"\xe2i\xcd\xcfh\x9eLD\xd31\xbf\xe3.\xa0\xf8\xad" +
	"\xe6\xe75\xefHD\xe31\xcfE\xe5\x9c\xd1\xfc\x82\xe6" +
	"\xa9d!r\xdc\xaf\\\x07\x14\x7f\xa2\xe4\x84\x104\xd2" +
	"\x1d\x05\xa6\x01\xf3\"'\x81\xe2\x05\x1d\x9e\xd6<\x93*" +
	"0\x03\x98I1\x00L\x08\xc9bV\xe3\xcet\x81\x9d" +
	"\xda\\BW\x99\xd0\xbcG\xf3\xaeL\x81]\x80\x99\x13" +
	"\xba\x9a\xac\xe6+4\xcfv\x16\x98\x05\xcc\x1b\xc5\xa3@" +
	"q\x85\xe6\xb7h\x9e\xeb*0\x07\x98\xab\xc5n\xa08" +
	"\xa4\xf9z\xcd\xbb\xb3\x05v\x03\xe6\xed\xe2\x19\xa0\xb8^" +
	"\xf3\xad\x9a\xe7s\x05\xe6\x01sT\xe8\xaem\xd1\xfc!" +
	"\xcd{\xba\x0b\xec\x01\xcc\x07\"~\xbf\xe6\xb3B0\x1f" +
	"\x04N)\x16\xc6\xd4\xac=5W\x0f*Z\x88M\xe6" +
	";\x15\xbb\xee[\x15\xb0\xd6\x14g\xbf\xad\xc7\xcd\x9e\xf6" +
	"\x85\xc2\x1e0\xac\xd5\xed\xa0\xe4V\x1b\xe8\xafl\xb5\xea" +
	"\xb3q\x8e\x8a\xed\xcd\x95\xed\x09\x17\xd2\xf5\x9b0\xef7" +
	"j6\xf3-\x85\x81\xcc\x83\x1b]\xcf\x99q\xaa\xb17" +
	"Jv\xddw\xaa\x96\x8f\x94\xe3\xc64\xef\xb9\xe5\xd8>" +
	"\xfd\xf5)\xb7\xd62\x93\xd5\xd4\x9flY\xa4\xa7%]" +
	"02\x8b]\x9d\xf2\x1a5\xdffi\xdcj\x94]\xab" +
	"\xd4\xf6\xc5\xcdg\xc8\x97\xb6\xd9\x8d\x16\xae\xcd\xda\x15\xdb" +
	"\xb3X\x1e\x0f&\xcb\xce\xd46\xd9\xf6\xd0j*\x9dm" +
	"\x87\xc6\x16\xb9|h\xdd\x99\x89\x96\x98v\xe8?yq" +
	"\xf0\x92\xa7T\x82\xedK\x9c\x03\x91\xc9T6\xde\xac\xa3" +
	"\x03\x80\xda$\xa9\xb6\xb7m\xd6;\xf5\"\xda*\xa9v" +
	"\xc462\x94^\xc1\xdb%\xd5\xbd\"\xee}\x9c\xf8R" +
	"\xef\xffn\xd6{*v\xbdn\xcd\xb4\xf5\xf7Z\x05G" +
	"\x95\xe9\xb5\x9f\x8d\xce\xeb\x1b\xd0Y\x8dec\x00\x85a" +
	"L\x00\xf9\xddu\xb7\x1a\xbf\x0f\xa0\xf5?\xeb\xd7\xbeS" +
	"\xa2>\x0c\xeeh\xc8K\xd9\xd3Qvc$\xca\x9e\xd9" +
	"\x05\xec\x09\xaasUw\xa1\x1a\xce[e\xa7d\xf9\x0e" +
	"d\xdb1\xf2Z\xd7\x03\xed+\xae\xa8\xe5\xad+J\xff" +
	"\xb5nyc\xd5\x1a\x88\xd4\x9c\xdd\x88\x15\x17],\x7f" +
	"\x06\x00\x00\xff\xffl\xe5\x09T"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_85d3acc39d94e0f8,
		Nodes: []uint64{
			0x8cc20228b0f1020d,
			0xa7c7ee760866c493,
			0xb1092b0e00ae75e5,
			0xb6507620d585d9aa,
			0xbbc6975bdbf2ac03,
			0xe35eff8ed54464f6,
			0xe5ef7577388ccd38,
		},
		Compressed: true,
	})
}
