// Code generated by capnpc-go. DO NOT EDIT.

package datura

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type Artifact capnp.Struct

// Artifact_TypeID is the unique identifier for the type Artifact.
const Artifact_TypeID = 0xb1092b0e00ae75e5

func NewArtifact(s *capnp.Segment) (Artifact, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 8})
	return Artifact(st), err
}

func NewRootArtifact(s *capnp.Segment) (Artifact, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 8})
	return Artifact(st), err
}

func ReadRootArtifact(msg *capnp.Message) (Artifact, error) {
	root, err := msg.Root()
	return Artifact(root.Struct()), err
}

func (s Artifact) String() string {
	str, _ := text.Marshal(0xb1092b0e00ae75e5, capnp.Struct(s))
	return str
}

func (s Artifact) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Artifact) DecodeFromPtr(p capnp.Ptr) Artifact {
	return Artifact(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Artifact) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Artifact) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Artifact) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Artifact) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Artifact) Uuid() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Artifact) HasUuid() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Artifact) UuidBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Artifact) SetUuid(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Artifact) Timestamp() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s Artifact) SetTimestamp(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s Artifact) Error() (Artifact_Error, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return Artifact_Error(p.Struct()), err
}

func (s Artifact) HasError() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Artifact) SetError(v Artifact_Error) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewError sets the error field to a newly
// allocated Artifact_Error struct, preferring placement in s's segment.
func (s Artifact) NewError() (Artifact_Error, error) {
	ss, err := NewArtifact_Error(capnp.Struct(s).Segment())
	if err != nil {
		return Artifact_Error{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Artifact) Type() Artifact_Type {
	return Artifact_Type(capnp.Struct(s).Uint16(8))
}

func (s Artifact) SetType(v Artifact_Type) {
	capnp.Struct(s).SetUint16(8, uint16(v))
}

func (s Artifact) Origin() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Artifact) HasOrigin() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Artifact) OriginBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Artifact) SetOrigin(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Artifact) Destination() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Artifact) HasDestination() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Artifact) DestinationBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Artifact) SetDestination(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Artifact) Role() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s Artifact) HasRole() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Artifact) RoleBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s Artifact) SetRole(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s Artifact) Scope() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s Artifact) HasScope() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Artifact) ScopeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s Artifact) SetScope(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s Artifact) Attributes() (Artifact_Attribute_List, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return Artifact_Attribute_List(p.List()), err
}

func (s Artifact) HasAttributes() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s Artifact) SetAttributes(v Artifact_Attribute_List) error {
	return capnp.Struct(s).SetPtr(6, v.ToPtr())
}

// NewAttributes sets the attributes field to a newly
// allocated Artifact_Attribute_List, preferring placement in s's segment.
func (s Artifact) NewAttributes(n int32) (Artifact_Attribute_List, error) {
	l, err := NewArtifact_Attribute_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Artifact_Attribute_List{}, err
	}
	err = capnp.Struct(s).SetPtr(6, l.ToPtr())
	return l, err
}
func (s Artifact) Payload() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return []byte(p.Data()), err
}

func (s Artifact) HasPayload() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s Artifact) SetPayload(v []byte) error {
	return capnp.Struct(s).SetData(7, v)
}

// Artifact_List is a list of Artifact.
type Artifact_List = capnp.StructList[Artifact]

// NewArtifact creates a new list of Artifact.
func NewArtifact_List(s *capnp.Segment, sz int32) (Artifact_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 8}, sz)
	return capnp.StructList[Artifact](l), err
}

// Artifact_Future is a wrapper for a Artifact promised by a client call.
type Artifact_Future struct{ *capnp.Future }

func (f Artifact_Future) Struct() (Artifact, error) {
	p, err := f.Future.Ptr()
	return Artifact(p.Struct()), err
}
func (p Artifact_Future) Error() Artifact_Error_Future {
	return Artifact_Error_Future{Future: p.Future.Field(1, nil)}
}

type Artifact_Error capnp.Struct

// Artifact_Error_TypeID is the unique identifier for the type Artifact_Error.
const Artifact_Error_TypeID = 0xb6507620d585d9aa

func NewArtifact_Error(s *capnp.Segment) (Artifact_Error, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return Artifact_Error(st), err
}

func NewRootArtifact_Error(s *capnp.Segment) (Artifact_Error, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return Artifact_Error(st), err
}

func ReadRootArtifact_Error(msg *capnp.Message) (Artifact_Error, error) {
	root, err := msg.Root()
	return Artifact_Error(root.Struct()), err
}

func (s Artifact_Error) String() string {
	str, _ := text.Marshal(0xb6507620d585d9aa, capnp.Struct(s))
	return str
}

func (s Artifact_Error) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Artifact_Error) DecodeFromPtr(p capnp.Ptr) Artifact_Error {
	return Artifact_Error(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Artifact_Error) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Artifact_Error) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Artifact_Error) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Artifact_Error) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Artifact_Error) Type() Artifact_Error_Type {
	return Artifact_Error_Type(capnp.Struct(s).Uint16(0))
}

func (s Artifact_Error) SetType(v Artifact_Error_Type) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s Artifact_Error) Timestamp() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s Artifact_Error) SetTimestamp(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s Artifact_Error) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Artifact_Error) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Artifact_Error) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Artifact_Error) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Artifact_Error_List is a list of Artifact_Error.
type Artifact_Error_List = capnp.StructList[Artifact_Error]

// NewArtifact_Error creates a new list of Artifact_Error.
func NewArtifact_Error_List(s *capnp.Segment, sz int32) (Artifact_Error_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[Artifact_Error](l), err
}

// Artifact_Error_Future is a wrapper for a Artifact_Error promised by a client call.
type Artifact_Error_Future struct{ *capnp.Future }

func (f Artifact_Error_Future) Struct() (Artifact_Error, error) {
	p, err := f.Future.Ptr()
	return Artifact_Error(p.Struct()), err
}

type Artifact_Error_Type uint16

// Artifact_Error_Type_TypeID is the unique identifier for the type Artifact_Error_Type.
const Artifact_Error_Type_TypeID = 0xe35eff8ed54464f6

// Values of Artifact_Error_Type.
const (
	Artifact_Error_Type_unknown    Artifact_Error_Type = 0
	Artifact_Error_Type_validation Artifact_Error_Type = 1
)

// String returns the enum's constant name.
func (c Artifact_Error_Type) String() string {
	switch c {
	case Artifact_Error_Type_unknown:
		return "unknown"
	case Artifact_Error_Type_validation:
		return "validation"

	default:
		return ""
	}
}

// Artifact_Error_TypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func Artifact_Error_TypeFromString(c string) Artifact_Error_Type {
	switch c {
	case "unknown":
		return Artifact_Error_Type_unknown
	case "validation":
		return Artifact_Error_Type_validation

	default:
		return 0
	}
}

type Artifact_Error_Type_List = capnp.EnumList[Artifact_Error_Type]

func NewArtifact_Error_Type_List(s *capnp.Segment, sz int32) (Artifact_Error_Type_List, error) {
	return capnp.NewEnumList[Artifact_Error_Type](s, sz)
}

type Artifact_Type uint16

// Artifact_Type_TypeID is the unique identifier for the type Artifact_Type.
const Artifact_Type_TypeID = 0xbbc6975bdbf2ac03

// Values of Artifact_Type.
const (
	Artifact_Type_json Artifact_Type = 0
)

// String returns the enum's constant name.
func (c Artifact_Type) String() string {
	switch c {
	case Artifact_Type_json:
		return "json"

	default:
		return ""
	}
}

// Artifact_TypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func Artifact_TypeFromString(c string) Artifact_Type {
	switch c {
	case "json":
		return Artifact_Type_json

	default:
		return 0
	}
}

type Artifact_Type_List = capnp.EnumList[Artifact_Type]

func NewArtifact_Type_List(s *capnp.Segment, sz int32) (Artifact_Type_List, error) {
	return capnp.NewEnumList[Artifact_Type](s, sz)
}

type Artifact_Attribute capnp.Struct

// Artifact_Attribute_TypeID is the unique identifier for the type Artifact_Attribute.
const Artifact_Attribute_TypeID = 0xe5ef7577388ccd38

func NewArtifact_Attribute(s *capnp.Segment) (Artifact_Attribute, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Artifact_Attribute(st), err
}

func NewRootArtifact_Attribute(s *capnp.Segment) (Artifact_Attribute, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Artifact_Attribute(st), err
}

func ReadRootArtifact_Attribute(msg *capnp.Message) (Artifact_Attribute, error) {
	root, err := msg.Root()
	return Artifact_Attribute(root.Struct()), err
}

func (s Artifact_Attribute) String() string {
	str, _ := text.Marshal(0xe5ef7577388ccd38, capnp.Struct(s))
	return str
}

func (s Artifact_Attribute) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Artifact_Attribute) DecodeFromPtr(p capnp.Ptr) Artifact_Attribute {
	return Artifact_Attribute(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Artifact_Attribute) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Artifact_Attribute) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Artifact_Attribute) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Artifact_Attribute) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Artifact_Attribute) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Artifact_Attribute) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Artifact_Attribute) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Artifact_Attribute) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Artifact_Attribute) Value() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Artifact_Attribute) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Artifact_Attribute) ValueBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Artifact_Attribute) SetValue(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// Artifact_Attribute_List is a list of Artifact_Attribute.
type Artifact_Attribute_List = capnp.StructList[Artifact_Attribute]

// NewArtifact_Attribute creates a new list of Artifact_Attribute.
func NewArtifact_Attribute_List(s *capnp.Segment, sz int32) (Artifact_Attribute_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Artifact_Attribute](l), err
}

// Artifact_Attribute_Future is a wrapper for a Artifact_Attribute promised by a client call.
type Artifact_Attribute_Future struct{ *capnp.Future }

func (f Artifact_Attribute_Future) Struct() (Artifact_Attribute, error) {
	p, err := f.Future.Ptr()
	return Artifact_Attribute(p.Struct()), err
}

const schema_85d3acc39d94e0f8 = "x\xda|\x93Ah+U\x14\x86\xff\xff\xde\x99I\x02" +
	"\xc9\x9b\x8c3b\x145U\xba\xe8\x8b\xbe\x92\xd7>\xe8" +
	"\xe3m|--X\xe8\"\xb7\xd3\x85V\x10\xa6\xcdX" +
	"\xc6\xa6\x99\x90LZ\xb2\xea\xaa\x0bA])\xe2\xa2[" +
	"A\xa9\x8a\x1b7\xee\x14\xdc\xb9\x92.D\x04A\x8a\xe8" +
	"F\xecB\xdd\x8d\xdcI3\x0db\xdf\xf2~\x9c\xf3\x9f" +
	"s\xfe\x7f\xa6i\x88\x87\xc6\xdd\xca\xaf\x16\x84j\x99\xd6" +
	"\xdf\x17\xc3\xcfn\xbdP\xfaB\xd9\x14\xe9??\xbfw" +
	"\xfa\xcd\xd9\xf7'0\x8b\x05\xc0}U~\xed\x06r\x09" +
	"X<\x91K\x02L?\xf9\xe1\xe4|\xe6\xb0\xf5%T" +
	"\x8db\xd2iR\xd7\xfed^\xba\xbf\x99O\x00\xee\x9f" +
	"\xe6\xe7`*\xcf.\x7f|\xed\x83o\xbf\x82S\xcb+" +
	"A\xf7\x1d\xebw\xf7CK7\xbco\xd5\xc1\xf4\xaf\xf6" +
	"\xea\xf9\xbb\xe9\xeb\xbf\xc0yV\\\xcb\x83\x8boYO" +
	"1\xaf\\\x02\xd3\xfb\xdf\xbd}\xffh\xf8\xc7\x05\x9c\x1a" +
	"\xf3\xd1\xa2\x00,\x9eZ\x8f\xd1\xfd4+\xfd\xd8:\xc2" +
	"Gi\xd0O\xa27\x82\xddD\xcc\xef\x06\xbdn\xef\xc1" +
	"\xf2\xd5\x1b\xaa\xcc\xa9#\x1cgaj\xcdJcjD" +
	"i\xb3\xbe\xd6\xef\xc7}{k\xd4\x0b\xd3\xe5$\xe9G" +
	";\xc3\x04\x0c\xd5\x9c4\x00\x83\x80[b\x03\xf0\x0dJ" +
	"\xfaU\x0a\x92\x1e5\xaep\x13\xf0\xcb\x1a\xd7(\xe8\x08" +
	"z\x14\x80\xfb8\x17\x00\xbf\xaa\xf9\xd3\x9aK\xc3\xa3\x04" +
	"\xdc'3\x19O\xf3\x19\xcd\x0d\xe1\xd1\x00\xdcg\xf8\x00" +
	"\xf0k\x9a\xcfjnJ\x8f&\xe0>\xc7\x1d\xc0\x9f\xd1" +
	"\xfcE\xcd-\xc3\xa3\x05\xb8\xb73\x9dY\xcd\x9b\x9a\x17" +
	"L/\x0b\xe6N6wN\xf3{\x9a\x17-\x8fE\xc0" +
	"\xbd\xcbm\xc0oj\xbe\xa1y\xa9\xe0\xb1\x04\xb8\xeb\\" +
	"\x01\xfcU\xcd[\x14\xb4\x87\xc3\xa8\xcd2\x04\xcb`\x9a" +
	"D\x07\xe1 \x09\x0e\xc0\x1eM\x08\x9a`=\xd4F\xb1" +
	":\x9d\x1e\xab\xa0\x9d\x8cz!\xedk\x87A\xda\xe0K" +
	"q?\xda\x8b\xba\xb9b;\x1c$Q7HP\x88\xe2" +
	"\x9c\xda\xfd\xb8\x13N\x1e\xf5\xc1n\xdc\xcb_i0\x09" +
	"C\x86\x03\xde\x02[\x92\xac^G\x07jx\xdc\x0bF" +
	"\x9d8h\xb3\x02\xc1\x8a\xee\xba\xe1\x93\x98\x1f\xe7\xac\x0c" +
	"N\x7f\x8bld\xc1\xab\xf2$lg\xad\x01\xa8\x87\x92" +
	"jC\xd0\xb9\x8a\xdaY\xdf\x04\xd4\xcb\x92jK\x90\"" +
	"\x8b\xd9Q+\x80\xda\x90T\xaf\x88\xdc\x82\\xl\xc1" +
	"\xff\xb9x|\x10\x0e\x06\xc1\xde\xd4\x997-\x9cm\xd6" +
	"\"\x95\x91\xcd3\x1b\x80\xfd\xe6 \xee\xe6\x1d\xf2\xbf\x1d" +
	"\xd9\x85\xf3[#9\xee+f}\xce\x8a\xde\xc6)m" +
	"\x03\xc7\xc3\xee~7>\xea\xa6\x87A'j\x07I\x04" +
	"\xf9(\xb9\xc9\xdf\xc0\xb1Zn\xd1\xed\xe7\x015+\xa9" +
	"\x9aS\x16\xddY\x00\xd4\x9c\xa4\xba'X\xd8\x0fGy" +
	"\xa8\x87Ag\x98_\xfbo\x00\x00\x00\xff\xff\x11\xd2\x17" +
	"H"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_85d3acc39d94e0f8,
		Nodes: []uint64{
			0xb1092b0e00ae75e5,
			0xb6507620d585d9aa,
			0xbbc6975bdbf2ac03,
			0xe35eff8ed54464f6,
			0xe5ef7577388ccd38,
		},
		Compressed: true,
	})
}
